### ISSUE TITLE
You can use sluggable in the model directly then you didn't need to handle it in controller

### ISSUE THREAD

**Issue by mhmodmonim** [alhaithamkamal/alhaithamkamalali-gmail.com#1]
another not check this issue https://github.com/AhmedGalaldev/laravellabes/issues/3#issue-589399744

https://github.com/alhaithamkamal/alhaithamkamalali-gmail.com/blob/52f11eb2e41f644e993cf9d4810b8d262415e3cf/app/Http/Controllers/PostController.php#L44-L50

**Comment by zeyadsaleh** [comment]
I don't know why i keep forgetting removing my mistakes :'D , i know that either i was just stuck at some point and I've tried somethings like that and i forgot to remove it, sorry about that.

I did use sluggable in the model by the way and it worked perfectly fine.

right now I'm doing the bonus of Lab2 of anything else in the required lab1 or 2 need please tell me.

thank you for you handy comments :)

**Comment by alhaithamkamal** [comment]
I got it Thanks ya bashmohandes
